// Code generated by protoc-gen-gogo.
// source: server.proto
// DO NOT EDIT!

/*
Package proto_rpc is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	GetAllMappingMsg
	Mapping
	GetAllMappingResponse
	GetMappingMsg
	GetMappingResponse
	CreateMappingMsg
	CreateMappingResponse
	GetIdentityMsg
	ObjectCountResponse
	GetObjectMsg
	OrderBy
	DBSession
	CreateObjectsMsg
	CreateIdentityMsg
	ObjectResponse
	MultiObjectResponse
	ObjectResponseData
	Object
*/
package proto_rpc

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// GetAllMappingMsg represents a request for recent mappings
type GetAllMappingMsg struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" structs:"name,omitempty" mapstructure:"name,omitempty"`
	Limit int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" structs:"limit,omitempty" mapstructure:"limit,omitempty"`
}

func (m *GetAllMappingMsg) Reset()                    { *m = GetAllMappingMsg{} }
func (m *GetAllMappingMsg) String() string            { return proto.CompactTextString(m) }
func (*GetAllMappingMsg) ProtoMessage()               {}
func (*GetAllMappingMsg) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{0} }

func (m *GetAllMappingMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetAllMappingMsg) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

// Mapping represents a single mapping
type Mapping struct {
	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" structs:"name,omitempty" mapstructure:"name,omitempty"`
	Mapping []byte `protobuf:"bytes,2,opt,name=mapping,proto3" json:"mapping,omitempty" structs:"mapping,omitempty" mapstructure:"mapping,omitempty"`
}

func (m *Mapping) Reset()                    { *m = Mapping{} }
func (m *Mapping) String() string            { return proto.CompactTextString(m) }
func (*Mapping) ProtoMessage()               {}
func (*Mapping) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{1} }

func (m *Mapping) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Mapping) GetMapping() []byte {
	if m != nil {
		return m.Mapping
	}
	return nil
}

// GetAllMappingResponse represents a response container all mappings encoded in JSON
type GetAllMappingResponse struct {
	Mappings []*Mapping `protobuf:"bytes,1,rep,name=mappings" json:"mappings,omitempty" structs:"mappings,omitempty" mapstructure:"mappings,omitempty"`
}

func (m *GetAllMappingResponse) Reset()                    { *m = GetAllMappingResponse{} }
func (m *GetAllMappingResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllMappingResponse) ProtoMessage()               {}
func (*GetAllMappingResponse) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{2} }

func (m *GetAllMappingResponse) GetMappings() []*Mapping {
	if m != nil {
		return m.Mappings
	}
	return nil
}

// GetMappingMsg represents a request for a mapping
type GetMappingMsg struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" structs:"name,omitempty" mapstructure:"name,omitempty"`
}

func (m *GetMappingMsg) Reset()                    { *m = GetMappingMsg{} }
func (m *GetMappingMsg) String() string            { return proto.CompactTextString(m) }
func (*GetMappingMsg) ProtoMessage()               {}
func (*GetMappingMsg) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{3} }

func (m *GetMappingMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// GetMappingResponse represents a response containing a mapping
type GetMappingResponse struct {
	Mapping []byte `protobuf:"bytes,1,opt,name=mapping,proto3" json:"mapping,omitempty" structs:"mapping,omitempty" mapstructure:"mapping,omitempty"`
}

func (m *GetMappingResponse) Reset()                    { *m = GetMappingResponse{} }
func (m *GetMappingResponse) String() string            { return proto.CompactTextString(m) }
func (*GetMappingResponse) ProtoMessage()               {}
func (*GetMappingResponse) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{4} }

func (m *GetMappingResponse) GetMapping() []byte {
	if m != nil {
		return m.Mapping
	}
	return nil
}

// CreateMappingMsg represents mapping creation parameters
type CreateMappingMsg struct {
	// The name of the mapping
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" structs:"name,omitempty" mapstructure:"name,omitempty"`
	// JSON mapping structure as bytes
	Mapping []byte `protobuf:"bytes,1,opt,name=mapping,proto3" json:"mapping,omitempty" structs:"mapping,omitempty" mapstructure:"mapping,omitempty"`
}

func (m *CreateMappingMsg) Reset()                    { *m = CreateMappingMsg{} }
func (m *CreateMappingMsg) String() string            { return proto.CompactTextString(m) }
func (*CreateMappingMsg) ProtoMessage()               {}
func (*CreateMappingMsg) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{5} }

func (m *CreateMappingMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateMappingMsg) GetMapping() []byte {
	if m != nil {
		return m.Mapping
	}
	return nil
}

type CreateMappingResponse struct {
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"id,omitempty" structs:"id,omitempty" mapstructure:"id,omitempty"`
}

func (m *CreateMappingResponse) Reset()                    { *m = CreateMappingResponse{} }
func (m *CreateMappingResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateMappingResponse) ProtoMessage()               {}
func (*CreateMappingResponse) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{6} }

func (m *CreateMappingResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// GetIdentityMsg represents an identity request message
type GetIdentityMsg struct {
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id,omitempty" structs:"id,omitempty" mapstructure:"id,omitempty"`
}

func (m *GetIdentityMsg) Reset()                    { *m = GetIdentityMsg{} }
func (m *GetIdentityMsg) String() string            { return proto.CompactTextString(m) }
func (*GetIdentityMsg) ProtoMessage()               {}
func (*GetIdentityMsg) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{7} }

func (m *GetIdentityMsg) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// ObjectCountResponse represents object counts
type ObjectCountResponse struct {
	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *ObjectCountResponse) Reset()                    { *m = ObjectCountResponse{} }
func (m *ObjectCountResponse) String() string            { return proto.CompactTextString(m) }
func (*ObjectCountResponse) ProtoMessage()               {}
func (*ObjectCountResponse) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{8} }

func (m *ObjectCountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// GetObjectMsg represents query parameters for retrieving objects
type GetObjectMsg struct {
	Query   []byte     `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty" structs:"query,omitempty" mapstructure:"query,omitempty"`
	Owner   string     `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty" structs:"owner,omitempty" mapstructure:"owner,omitempty"`
	Creator string     `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty" structs:"creator,omitempty" mapstructure:"creator,omitempty"`
	Order   []*OrderBy `protobuf:"bytes,4,rep,name=order" json:"order,omitempty" structs:"order,omitempty" mapstructure:"order,omitempty"`
	Limit   int32      `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty" structs:"limit,omitempty" mapstructure:"limit,omitempty"`
}

func (m *GetObjectMsg) Reset()                    { *m = GetObjectMsg{} }
func (m *GetObjectMsg) String() string            { return proto.CompactTextString(m) }
func (*GetObjectMsg) ProtoMessage()               {}
func (*GetObjectMsg) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{9} }

func (m *GetObjectMsg) GetQuery() []byte {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *GetObjectMsg) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GetObjectMsg) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *GetObjectMsg) GetOrder() []*OrderBy {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *GetObjectMsg) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

// OrderBy represents how a field is ordered in a query
type OrderBy struct {
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty" structs:"field,omitempty" mapstructure:"field,omitempty"`
	Order int32  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty" structs:"order,omitempty" mapstructure:"order,omitempty"`
}

func (m *OrderBy) Reset()                    { *m = OrderBy{} }
func (m *OrderBy) String() string            { return proto.CompactTextString(m) }
func (*OrderBy) ProtoMessage()               {}
func (*OrderBy) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{10} }

func (m *OrderBy) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *OrderBy) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

// DBSession represents a database session request body
type DBSession struct {
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id,omitempty" structs:"id,omitempty" mapstructure:"id,omitempty"`
}

func (m *DBSession) Reset()                    { *m = DBSession{} }
func (m *DBSession) String() string            { return proto.CompactTextString(m) }
func (*DBSession) ProtoMessage()               {}
func (*DBSession) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{11} }

func (m *DBSession) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// CreateObjects represents a collection of objects to be created
type CreateObjectsMsg struct {
	Objects []*Object `protobuf:"bytes,1,rep,name=objects" json:"objects,omitempty" structs:"objects,omitempty" mapstructure:"objects,omitempty"`
}

func (m *CreateObjectsMsg) Reset()                    { *m = CreateObjectsMsg{} }
func (m *CreateObjectsMsg) String() string            { return proto.CompactTextString(m) }
func (*CreateObjectsMsg) ProtoMessage()               {}
func (*CreateObjectsMsg) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{12} }

func (m *CreateObjectsMsg) GetObjects() []*Object {
	if m != nil {
		return m.Objects
	}
	return nil
}

// CreateIdentityMsg represents an identity of a person or organization
type CreateIdentityMsg struct {
	Email     string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" structs:"email,omitempty" mapstructure:"email,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" structs:"password,omitempty" mapstructure:"password,omitempty"`
	Developer bool   `protobuf:"varint,3,opt,name=developer,proto3" json:"developer,omitempty" structs:"developer,omitempty" mapstructure:"developer,omitempty"`
}

func (m *CreateIdentityMsg) Reset()                    { *m = CreateIdentityMsg{} }
func (m *CreateIdentityMsg) String() string            { return proto.CompactTextString(m) }
func (*CreateIdentityMsg) ProtoMessage()               {}
func (*CreateIdentityMsg) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{13} }

func (m *CreateIdentityMsg) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateIdentityMsg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateIdentityMsg) GetDeveloper() bool {
	if m != nil {
		return m.Developer
	}
	return false
}

// ObjectResponse defines a response about a single object
type ObjectResponse struct {
	Data  *ObjectResponseData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty" structs:"data,omitempty" mapstructure:"data,omitempty"`
	Links map[string]string   `protobuf:"bytes,2,rep,name=links" json:"links,omitempty" structs:"links,omitempty" mapstructure:"links,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *ObjectResponse) Reset()                    { *m = ObjectResponse{} }
func (m *ObjectResponse) String() string            { return proto.CompactTextString(m) }
func (*ObjectResponse) ProtoMessage()               {}
func (*ObjectResponse) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{14} }

func (m *ObjectResponse) GetData() *ObjectResponseData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ObjectResponse) GetLinks() map[string]string {
	if m != nil {
		return m.Links
	}
	return nil
}

// MultiObjectResponse describes a response of multiple objects
type MultiObjectResponse struct {
	Data  []*ObjectResponseData `protobuf:"bytes,1,rep,name=data" json:"data,omitempty" structs:"data,omitempty" mapstructure:"data,omitempty"`
	Links map[string]string     `protobuf:"bytes,2,rep,name=links" json:"links,omitempty" structs:"links,omitempty" mapstructure:"links,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *MultiObjectResponse) Reset()                    { *m = MultiObjectResponse{} }
func (m *MultiObjectResponse) String() string            { return proto.CompactTextString(m) }
func (*MultiObjectResponse) ProtoMessage()               {}
func (*MultiObjectResponse) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{15} }

func (m *MultiObjectResponse) GetData() []*ObjectResponseData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MultiObjectResponse) GetLinks() map[string]string {
	if m != nil {
		return m.Links
	}
	return nil
}

// ObjectResponse describes an object and related information
type ObjectResponseData struct {
	Type       string  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" structs:"type,omitempty" mapstructure:"type,omitempty"`
	ID         string  `protobuf:"bytes,2,opt,name=ID,proto3" json:"id,omitempty" structs:"id,omitempty" mapstructure:"id,omitempty"`
	Attributes *Object `protobuf:"bytes,3,opt,name=attributes" json:"attributes,omitempty" structs:"attributes,omitempty" mapstructure:"attributes,omitempty"`
}

func (m *ObjectResponseData) Reset()                    { *m = ObjectResponseData{} }
func (m *ObjectResponseData) String() string            { return proto.CompactTextString(m) }
func (*ObjectResponseData) ProtoMessage()               {}
func (*ObjectResponseData) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{16} }

func (m *ObjectResponseData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ObjectResponseData) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ObjectResponseData) GetAttributes() *Object {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// Object describes an object
type Object struct {
	ID          string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id,omitempty" structs:"id,omitempty" mapstructure:"id,omitempty"`
	OwnerID     string `protobuf:"bytes,2,opt,name=ownerID,proto3" json:"owner_id,omitempty" structs:"ownerId,omitempty" mapstructure:"ownerId,omitempty"`
	CreatorID   string `protobuf:"bytes,3,opt,name=creatorID,proto3" json:"creator_id,omitempty" structs:"creatorId,omitempty" mapstructure:"creatorId,omitempty"`
	PartitionID string `protobuf:"bytes,4,opt,name=partitionID,proto3" json:"partition_id,omitempty" structs:"partitionId,omitempty" mapstructure:"partitionId,omitempty"`
	Key         string `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty" structs:"key,omitempty" mapstructure:"key,omitempty"`
	Value       string `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty" structs:"value,omitempty" mapstructure:"value,omitempty"`
	Protected   bool   `protobuf:"varint,7,opt,name=protected,proto3" json:"protected,omitempty" structs:"protected,omitempty" mapstructure:"protected,omitempty"`
	RefOnly     bool   `protobuf:"varint,8,opt,name=refOnly,proto3" json:"ref_only,omitempty" structs:"refOnly,omitempty" mapstructure:"refOnly,omitempty"`
	Timestamp   int64  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty" structs:"timestamp,omitempty" mapstructure:"timestamp,omitempty"`
	PrevHash    string `protobuf:"bytes,10,opt,name=prevHash,proto3" json:"prev_hash,omitempty" structs:"prevHash,omitempty" mapstructure:"prevHash,omitempty"`
	PeerHash    string `protobuf:"bytes,11,opt,name=peerHash,proto3" json:"peer_hash,omitempty" structs:"peerHash,omitempty" mapstructure:"peerHash,omitempty"`
	Hash        string `protobuf:"bytes,12,opt,name=hash,proto3" json:"hash,omitempty" structs:"hash,omitempty" mapstructure:"hash,omitempty"`
	Ref1        string `protobuf:"bytes,13,opt,name=ref1,proto3" json:"ref1,omitempty" structs:"ref1,omitempty" mapstructure:"ref1,omitempty"`
	Ref2        string `protobuf:"bytes,14,opt,name=ref2,proto3" json:"ref2,omitempty" structs:"ref2,omitempty" mapstructure:"ref2,omitempty"`
	Ref3        string `protobuf:"bytes,15,opt,name=ref3,proto3" json:"ref3,omitempty" structs:"ref3,omitempty" mapstructure:"ref3,omitempty"`
	Ref4        string `protobuf:"bytes,16,opt,name=ref4,proto3" json:"ref4,omitempty" structs:"ref4,omitempty" mapstructure:"ref4,omitempty"`
	Ref5        string `protobuf:"bytes,17,opt,name=ref5,proto3" json:"ref5,omitempty" structs:"ref5,omitempty" mapstructure:"ref5,omitempty"`
	Ref6        string `protobuf:"bytes,18,opt,name=ref6,proto3" json:"ref6,omitempty" structs:"ref6,omitempty" mapstructure:"ref6,omitempty"`
	Ref7        string `protobuf:"bytes,19,opt,name=ref7,proto3" json:"ref7,omitempty" structs:"ref7,omitempty" mapstructure:"ref7,omitempty"`
	Ref8        string `protobuf:"bytes,20,opt,name=ref8,proto3" json:"ref8,omitempty" structs:"ref8,omitempty" mapstructure:"ref8,omitempty"`
	Ref9        string `protobuf:"bytes,21,opt,name=ref9,proto3" json:"ref9,omitempty" structs:"ref9,omitempty" mapstructure:"ref9,omitempty"`
	Ref10       string `protobuf:"bytes,22,opt,name=ref10,proto3" json:"ref10,omitempty" structs:"ref10,omitempty" mapstructure:"ref10,omitempty"`
}

func (m *Object) Reset()                    { *m = Object{} }
func (m *Object) String() string            { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()               {}
func (*Object) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{17} }

func (m *Object) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Object) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *Object) GetCreatorID() string {
	if m != nil {
		return m.CreatorID
	}
	return ""
}

func (m *Object) GetPartitionID() string {
	if m != nil {
		return m.PartitionID
	}
	return ""
}

func (m *Object) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Object) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Object) GetProtected() bool {
	if m != nil {
		return m.Protected
	}
	return false
}

func (m *Object) GetRefOnly() bool {
	if m != nil {
		return m.RefOnly
	}
	return false
}

func (m *Object) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Object) GetPrevHash() string {
	if m != nil {
		return m.PrevHash
	}
	return ""
}

func (m *Object) GetPeerHash() string {
	if m != nil {
		return m.PeerHash
	}
	return ""
}

func (m *Object) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Object) GetRef1() string {
	if m != nil {
		return m.Ref1
	}
	return ""
}

func (m *Object) GetRef2() string {
	if m != nil {
		return m.Ref2
	}
	return ""
}

func (m *Object) GetRef3() string {
	if m != nil {
		return m.Ref3
	}
	return ""
}

func (m *Object) GetRef4() string {
	if m != nil {
		return m.Ref4
	}
	return ""
}

func (m *Object) GetRef5() string {
	if m != nil {
		return m.Ref5
	}
	return ""
}

func (m *Object) GetRef6() string {
	if m != nil {
		return m.Ref6
	}
	return ""
}

func (m *Object) GetRef7() string {
	if m != nil {
		return m.Ref7
	}
	return ""
}

func (m *Object) GetRef8() string {
	if m != nil {
		return m.Ref8
	}
	return ""
}

func (m *Object) GetRef9() string {
	if m != nil {
		return m.Ref9
	}
	return ""
}

func (m *Object) GetRef10() string {
	if m != nil {
		return m.Ref10
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAllMappingMsg)(nil), "proto_rpc.GetAllMappingMsg")
	proto.RegisterType((*Mapping)(nil), "proto_rpc.Mapping")
	proto.RegisterType((*GetAllMappingResponse)(nil), "proto_rpc.GetAllMappingResponse")
	proto.RegisterType((*GetMappingMsg)(nil), "proto_rpc.GetMappingMsg")
	proto.RegisterType((*GetMappingResponse)(nil), "proto_rpc.GetMappingResponse")
	proto.RegisterType((*CreateMappingMsg)(nil), "proto_rpc.CreateMappingMsg")
	proto.RegisterType((*CreateMappingResponse)(nil), "proto_rpc.CreateMappingResponse")
	proto.RegisterType((*GetIdentityMsg)(nil), "proto_rpc.GetIdentityMsg")
	proto.RegisterType((*ObjectCountResponse)(nil), "proto_rpc.ObjectCountResponse")
	proto.RegisterType((*GetObjectMsg)(nil), "proto_rpc.GetObjectMsg")
	proto.RegisterType((*OrderBy)(nil), "proto_rpc.OrderBy")
	proto.RegisterType((*DBSession)(nil), "proto_rpc.DBSession")
	proto.RegisterType((*CreateObjectsMsg)(nil), "proto_rpc.CreateObjectsMsg")
	proto.RegisterType((*CreateIdentityMsg)(nil), "proto_rpc.CreateIdentityMsg")
	proto.RegisterType((*ObjectResponse)(nil), "proto_rpc.ObjectResponse")
	proto.RegisterType((*MultiObjectResponse)(nil), "proto_rpc.MultiObjectResponse")
	proto.RegisterType((*ObjectResponseData)(nil), "proto_rpc.ObjectResponseData")
	proto.RegisterType((*Object)(nil), "proto_rpc.Object")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for API service

type APIClient interface {
	CreateIdentity(ctx context.Context, in *CreateIdentityMsg, opts ...grpc.CallOption) (*ObjectResponse, error)
	CreateObjects(ctx context.Context, in *CreateObjectsMsg, opts ...grpc.CallOption) (*MultiObjectResponse, error)
	CreateDBSession(ctx context.Context, in *DBSession, opts ...grpc.CallOption) (*DBSession, error)
	GetDBSession(ctx context.Context, in *DBSession, opts ...grpc.CallOption) (*DBSession, error)
	DeleteDBSession(ctx context.Context, in *DBSession, opts ...grpc.CallOption) (*DBSession, error)
	GetObjects(ctx context.Context, in *GetObjectMsg, opts ...grpc.CallOption) (*MultiObjectResponse, error)
	CountObjects(ctx context.Context, in *GetObjectMsg, opts ...grpc.CallOption) (*ObjectCountResponse, error)
	GetIdentity(ctx context.Context, in *GetIdentityMsg, opts ...grpc.CallOption) (*ObjectResponse, error)
	CreateMapping(ctx context.Context, in *CreateMappingMsg, opts ...grpc.CallOption) (*CreateMappingResponse, error)
	GetMapping(ctx context.Context, in *GetMappingMsg, opts ...grpc.CallOption) (*GetMappingResponse, error)
	GetAllMapping(ctx context.Context, in *GetAllMappingMsg, opts ...grpc.CallOption) (*GetAllMappingResponse, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) CreateIdentity(ctx context.Context, in *CreateIdentityMsg, opts ...grpc.CallOption) (*ObjectResponse, error) {
	out := new(ObjectResponse)
	err := grpc.Invoke(ctx, "/proto_rpc.API/CreateIdentity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateObjects(ctx context.Context, in *CreateObjectsMsg, opts ...grpc.CallOption) (*MultiObjectResponse, error) {
	out := new(MultiObjectResponse)
	err := grpc.Invoke(ctx, "/proto_rpc.API/CreateObjects", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateDBSession(ctx context.Context, in *DBSession, opts ...grpc.CallOption) (*DBSession, error) {
	out := new(DBSession)
	err := grpc.Invoke(ctx, "/proto_rpc.API/CreateDBSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetDBSession(ctx context.Context, in *DBSession, opts ...grpc.CallOption) (*DBSession, error) {
	out := new(DBSession)
	err := grpc.Invoke(ctx, "/proto_rpc.API/GetDBSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteDBSession(ctx context.Context, in *DBSession, opts ...grpc.CallOption) (*DBSession, error) {
	out := new(DBSession)
	err := grpc.Invoke(ctx, "/proto_rpc.API/DeleteDBSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetObjects(ctx context.Context, in *GetObjectMsg, opts ...grpc.CallOption) (*MultiObjectResponse, error) {
	out := new(MultiObjectResponse)
	err := grpc.Invoke(ctx, "/proto_rpc.API/GetObjects", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CountObjects(ctx context.Context, in *GetObjectMsg, opts ...grpc.CallOption) (*ObjectCountResponse, error) {
	out := new(ObjectCountResponse)
	err := grpc.Invoke(ctx, "/proto_rpc.API/CountObjects", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetIdentity(ctx context.Context, in *GetIdentityMsg, opts ...grpc.CallOption) (*ObjectResponse, error) {
	out := new(ObjectResponse)
	err := grpc.Invoke(ctx, "/proto_rpc.API/GetIdentity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateMapping(ctx context.Context, in *CreateMappingMsg, opts ...grpc.CallOption) (*CreateMappingResponse, error) {
	out := new(CreateMappingResponse)
	err := grpc.Invoke(ctx, "/proto_rpc.API/CreateMapping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetMapping(ctx context.Context, in *GetMappingMsg, opts ...grpc.CallOption) (*GetMappingResponse, error) {
	out := new(GetMappingResponse)
	err := grpc.Invoke(ctx, "/proto_rpc.API/GetMapping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetAllMapping(ctx context.Context, in *GetAllMappingMsg, opts ...grpc.CallOption) (*GetAllMappingResponse, error) {
	out := new(GetAllMappingResponse)
	err := grpc.Invoke(ctx, "/proto_rpc.API/GetAllMapping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for API service

type APIServer interface {
	CreateIdentity(context.Context, *CreateIdentityMsg) (*ObjectResponse, error)
	CreateObjects(context.Context, *CreateObjectsMsg) (*MultiObjectResponse, error)
	CreateDBSession(context.Context, *DBSession) (*DBSession, error)
	GetDBSession(context.Context, *DBSession) (*DBSession, error)
	DeleteDBSession(context.Context, *DBSession) (*DBSession, error)
	GetObjects(context.Context, *GetObjectMsg) (*MultiObjectResponse, error)
	CountObjects(context.Context, *GetObjectMsg) (*ObjectCountResponse, error)
	GetIdentity(context.Context, *GetIdentityMsg) (*ObjectResponse, error)
	CreateMapping(context.Context, *CreateMappingMsg) (*CreateMappingResponse, error)
	GetMapping(context.Context, *GetMappingMsg) (*GetMappingResponse, error)
	GetAllMapping(context.Context, *GetAllMappingMsg) (*GetAllMappingResponse, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_CreateIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIdentityMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_rpc.API/CreateIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateIdentity(ctx, req.(*CreateIdentityMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateObjectsMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_rpc.API/CreateObjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateObjects(ctx, req.(*CreateObjectsMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateDBSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateDBSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_rpc.API/CreateDBSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateDBSession(ctx, req.(*DBSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetDBSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetDBSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_rpc.API/GetDBSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetDBSession(ctx, req.(*DBSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteDBSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteDBSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_rpc.API/DeleteDBSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteDBSession(ctx, req.(*DBSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_rpc.API/GetObjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetObjects(ctx, req.(*GetObjectMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CountObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CountObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_rpc.API/CountObjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CountObjects(ctx, req.(*GetObjectMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_rpc.API/GetIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetIdentity(ctx, req.(*GetIdentityMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMappingMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_rpc.API/CreateMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateMapping(ctx, req.(*CreateMappingMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMappingMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_rpc.API/GetMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetMapping(ctx, req.(*GetMappingMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetAllMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMappingMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetAllMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_rpc.API/GetAllMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetAllMapping(ctx, req.(*GetAllMappingMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_rpc.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIdentity",
			Handler:    _API_CreateIdentity_Handler,
		},
		{
			MethodName: "CreateObjects",
			Handler:    _API_CreateObjects_Handler,
		},
		{
			MethodName: "CreateDBSession",
			Handler:    _API_CreateDBSession_Handler,
		},
		{
			MethodName: "GetDBSession",
			Handler:    _API_GetDBSession_Handler,
		},
		{
			MethodName: "DeleteDBSession",
			Handler:    _API_DeleteDBSession_Handler,
		},
		{
			MethodName: "GetObjects",
			Handler:    _API_GetObjects_Handler,
		},
		{
			MethodName: "CountObjects",
			Handler:    _API_CountObjects_Handler,
		},
		{
			MethodName: "GetIdentity",
			Handler:    _API_GetIdentity_Handler,
		},
		{
			MethodName: "CreateMapping",
			Handler:    _API_CreateMapping_Handler,
		},
		{
			MethodName: "GetMapping",
			Handler:    _API_GetMapping_Handler,
		},
		{
			MethodName: "GetAllMapping",
			Handler:    _API_GetAllMapping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto.RegisterFile("server.proto", fileDescriptorServer) }

var fileDescriptorServer = []byte{
	// 1585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x99, 0x5d, 0x6f, 0xdc, 0x44,
	0x17, 0xc7, 0xe5, 0x4d, 0x36, 0xc9, 0x4e, 0xde, 0x27, 0x69, 0x1f, 0x37, 0xcf, 0xd3, 0x67, 0x23,
	0x8b, 0x8b, 0x22, 0x20, 0x6d, 0x37, 0x6f, 0x9b, 0xaa, 0x45, 0xed, 0x76, 0x4b, 0x58, 0xa9, 0x6d,
	0xd0, 0x20, 0x2a, 0xa0, 0x88, 0xe0, 0xec, 0x4e, 0x12, 0x93, 0x5d, 0xdb, 0xb5, 0x67, 0x53, 0x2d,
	0x37, 0x48, 0x08, 0x24, 0x24, 0x6e, 0x40, 0x42, 0xe2, 0x9e, 0x4b, 0x6e, 0xf8, 0x38, 0x08, 0x81,
	0xf6, 0x02, 0xc4, 0xcd, 0x72, 0xc7, 0x27, 0x40, 0xf3, 0xe2, 0x97, 0x19, 0x7b, 0x5c, 0xa8, 0xda,
	0xc0, 0x55, 0xe2, 0xf3, 0x3f, 0x9e, 0xdf, 0x99, 0x33, 0xe3, 0x73, 0xc6, 0x5e, 0x30, 0x13, 0xe2,
	0xe0, 0x14, 0x07, 0x6b, 0x7e, 0xe0, 0x11, 0x0f, 0x56, 0xd8, 0x9f, 0xfd, 0xc0, 0x6f, 0xaf, 0xbc,
	0x72, 0xe4, 0x90, 0xe3, 0xfe, 0xc1, 0x5a, 0xdb, 0xeb, 0x5d, 0x3e, 0xf2, 0x8e, 0xbc, 0xcb, 0x4c,
	0x3a, 0xe8, 0x1f, 0xb2, 0x2b, 0x76, 0xc1, 0xfe, 0xe3, 0x77, 0x5a, 0x3f, 0x19, 0x60, 0x61, 0x17,
	0x93, 0x5b, 0xdd, 0xee, 0x3d, 0xdb, 0xf7, 0x1d, 0xf7, 0xe8, 0x5e, 0x78, 0x04, 0x3f, 0x00, 0xe3,
	0xae, 0xdd, 0xc3, 0xa6, 0xb1, 0x6a, 0x5c, 0xaa, 0x34, 0xee, 0x8e, 0x86, 0xd5, 0x39, 0x7a, 0xfd,
	0xb2, 0xd7, 0x73, 0x08, 0xee, 0xf9, 0x64, 0xf0, 0xc7, 0xb0, 0xba, 0x15, 0x92, 0xa0, 0xdf, 0x26,
	0xe1, 0x35, 0x4b, 0x96, 0xac, 0xd5, 0x9e, 0xed, 0x73, 0xad, 0x1f, 0xe0, 0x8c, 0x8a, 0xd8, 0xc8,
	0x10, 0x83, 0x72, 0xd7, 0xe9, 0x39, 0xc4, 0x2c, 0xad, 0x1a, 0x97, 0xca, 0x8d, 0xbd, 0xd1, 0xb0,
	0x3a, 0xcf, 0x0c, 0x12, 0xa3, 0x1e, 0x33, 0x14, 0x4d, 0x85, 0xa8, 0x32, 0xe2, 0xa3, 0x5b, 0x3f,
	0x1b, 0x60, 0x52, 0xcc, 0xeb, 0x0c, 0x26, 0xe5, 0x81, 0xc9, 0x1e, 0x87, 0xb1, 0x69, 0xcd, 0x34,
	0xde, 0x1a, 0x0d, 0xab, 0x8b, 0xc2, 0x24, 0x71, 0xae, 0xc7, 0x9c, 0x8c, 0xaa, 0xa2, 0xb2, 0x0e,
	0x28, 0xa2, 0x58, 0xdf, 0x1a, 0xe0, 0x9c, 0xb4, 0x78, 0x08, 0x87, 0xbe, 0xe7, 0x86, 0x18, 0x7e,
	0x6e, 0x80, 0x29, 0xe1, 0x15, 0x9a, 0xc6, 0xea, 0xd8, 0xa5, 0xe9, 0x1a, 0x5c, 0x8b, 0x37, 0xc9,
	0x9a, 0x70, 0x6f, 0xbc, 0x3d, 0x1a, 0x56, 0x61, 0xe4, 0x27, 0x45, 0xf8, 0xaa, 0x1a, 0x61, 0xf8,
	0xc4, 0x10, 0xd3, 0x1e, 0x28, 0xa6, 0x5b, 0x8f, 0xc0, 0xec, 0x2e, 0x26, 0x67, 0xb9, 0xbb, 0xac,
	0xcf, 0x0c, 0x00, 0x13, 0x66, 0x9c, 0x94, 0xd4, 0xfa, 0x18, 0x67, 0xb2, 0x3e, 0xbf, 0x19, 0x60,
	0xe1, 0x76, 0x80, 0x6d, 0x82, 0x73, 0xa6, 0x5f, 0x3a, 0x8b, 0x7d, 0x78, 0x36, 0xf3, 0x0c, 0xc1,
	0x39, 0x69, 0x9a, 0x71, 0xc6, 0xdf, 0x05, 0xe3, 0xf7, 0x93, 0xa5, 0x7e, 0x6d, 0x34, 0xac, 0xce,
	0x38, 0x1d, 0x29, 0x82, 0x5a, 0x1c, 0x41, 0x5a, 0x50, 0xe1, 0x92, 0x86, 0xd8, 0x98, 0xd6, 0x31,
	0x98, 0xdb, 0xc5, 0xa4, 0xd5, 0xc1, 0x2e, 0x71, 0xc8, 0x80, 0x66, 0xf6, 0x01, 0x28, 0xb5, 0x9a,
	0xcf, 0x98, 0x55, 0x6a, 0x35, 0xad, 0x97, 0xc0, 0xd2, 0xde, 0xc1, 0x87, 0xb8, 0x4d, 0x6e, 0x7b,
	0x7d, 0x97, 0xc4, 0x93, 0x5b, 0x06, 0xe5, 0x36, 0x35, 0x30, 0xe2, 0x18, 0xe2, 0x17, 0xd6, 0xf7,
	0xe3, 0x60, 0x66, 0x17, 0x13, 0x7e, 0x03, 0x8d, 0x0a, 0x83, 0xf2, 0xa3, 0x3e, 0x0e, 0x06, 0x62,
	0x2d, 0x58, 0xa9, 0x63, 0x06, 0x4d, 0xa9, 0x53, 0x34, 0x35, 0x3c, 0x55, 0x46, 0x7c, 0x74, 0x8a,
	0xf1, 0x1e, 0xbb, 0x38, 0x10, 0xfb, 0x8a, 0x61, 0x98, 0x41, 0x83, 0x51, 0x34, 0x15, 0xa3, 0xca,
	0x88, 0x8f, 0x4e, 0xf7, 0x56, 0x9b, 0x2e, 0xb5, 0x17, 0x98, 0x63, 0x0c, 0xc4, 0xf6, 0x96, 0x30,
	0x69, 0xf6, 0x56, 0x46, 0x55, 0x61, 0x59, 0x07, 0x14, 0x51, 0xe0, 0x00, 0x94, 0xbd, 0xa0, 0x83,
	0x03, 0x73, 0x3c, 0x53, 0xc5, 0xf6, 0xa8, 0xbd, 0x31, 0x10, 0x73, 0xa5, 0x17, 0xba, 0xb9, 0xca,
	0x5a, 0x66, 0xae, 0x8a, 0x8c, 0x38, 0x31, 0x69, 0x52, 0xe5, 0xe7, 0xda, 0xa4, 0x7e, 0x30, 0xc0,
	0xa4, 0x98, 0x0a, 0x45, 0x1e, 0x3a, 0xb8, 0xdb, 0x11, 0xbb, 0x98, 0x21, 0x99, 0x41, 0x83, 0x54,
	0x34, 0x15, 0xa9, 0xca, 0x88, 0x8f, 0xce, 0x36, 0x0b, 0x4b, 0x6a, 0xaa, 0xfd, 0x3e, 0xfb, 0x04,
	0x5a, 0x6d, 0x50, 0x69, 0x36, 0xde, 0xc4, 0x61, 0xe8, 0x78, 0xee, 0x73, 0x7b, 0x3a, 0xbf, 0x89,
	0x8b, 0x2c, 0x7f, 0xe6, 0x42, 0xfa, 0xd0, 0x7d, 0x62, 0x80, 0x49, 0x8f, 0x5f, 0x8a, 0xf6, 0xb7,
	0x98, 0xde, 0x38, 0x4c, 0xe1, 0x5b, 0x57, 0x78, 0x69, 0xb6, 0x6e, 0x46, 0xcd, 0x4c, 0x3d, 0xe3,
	0x80, 0x22, 0xb0, 0xf5, 0x7b, 0x09, 0x2c, 0xf2, 0xc8, 0xd2, 0x55, 0x0a, 0x83, 0x32, 0xee, 0xd9,
	0x4e, 0x37, 0xbd, 0xc4, 0xcc, 0xa0, 0xc9, 0xbd, 0xa2, 0xa9, 0x01, 0xa8, 0x32, 0xe2, 0xa3, 0x43,
	0x02, 0xa6, 0x7c, 0x3b, 0x0c, 0x1f, 0x7b, 0x41, 0x47, 0x94, 0x04, 0xd6, 0xec, 0x23, 0x9b, 0xa6,
	0xd9, 0x67, 0x65, 0x95, 0x97, 0xe3, 0x81, 0x62, 0x12, 0x1c, 0x80, 0x4a, 0x07, 0x9f, 0xe2, 0xae,
	0xe7, 0x63, 0x5e, 0x20, 0xa6, 0x1a, 0x0f, 0x47, 0xc3, 0xea, 0x52, 0x6c, 0x94, 0xb8, 0x37, 0x63,
	0x6e, 0x8e, 0xae, 0x82, 0xf3, 0x5c, 0x50, 0x42, 0xb3, 0x7e, 0x2c, 0x81, 0x39, 0xbe, 0xb0, 0x71,
	0x85, 0xfe, 0x18, 0x8c, 0x77, 0x6c, 0x62, 0xb3, 0x4c, 0x4f, 0xd7, 0x2e, 0x66, 0x76, 0x40, 0xe4,
	0xd8, 0xb4, 0x89, 0xcd, 0x3b, 0x31, 0x75, 0xd7, 0x74, 0x62, 0x59, 0xca, 0x44, 0x27, 0xab, 0x88,
	0x81, 0xe1, 0x17, 0x06, 0x2d, 0x21, 0xee, 0x49, 0x68, 0x96, 0xd8, 0x26, 0x7c, 0x41, 0x1b, 0xc2,
	0xda, 0x5d, 0xea, 0x76, 0xc7, 0x25, 0xc1, 0x20, 0x2a, 0x34, 0xee, 0x49, 0xa8, 0x2d, 0x34, 0x92,
	0x96, 0x2d, 0x34, 0xb2, 0x8c, 0x78, 0x0c, 0x2b, 0x75, 0x00, 0x12, 0x0a, 0x5c, 0x00, 0x63, 0x27,
	0x98, 0x77, 0xa5, 0x0a, 0xa2, 0xff, 0xd2, 0x86, 0x76, 0x6a, 0x77, 0xfb, 0xe2, 0x68, 0x82, 0xf8,
	0xc5, 0xb5, 0x52, 0xdd, 0xb0, 0x7e, 0x2d, 0x81, 0xa5, 0x7b, 0xfd, 0x2e, 0x71, 0xb4, 0x09, 0x1e,
	0xfb, 0x67, 0x12, 0xfc, 0xa5, 0x92, 0xe0, 0x17, 0xd3, 0x87, 0xdc, 0x6c, 0xc0, 0xff, 0xee, 0x2c,
	0xff, 0x52, 0x02, 0x30, 0x9b, 0x37, 0x7a, 0x60, 0x24, 0x03, 0x5f, 0x3a, 0x2f, 0xd3, 0x6b, 0x4d,
	0x16, 0x65, 0x49, 0x0d, 0x5a, 0x51, 0x11, 0x1b, 0x59, 0x94, 0xe6, 0xd2, 0xb3, 0x2e, 0xcd, 0xf0,
	0x2b, 0x03, 0x00, 0x9b, 0x90, 0xc0, 0x39, 0xe8, 0x13, 0x1c, 0xb2, 0x7a, 0x90, 0x5b, 0x88, 0xdf,
	0x1f, 0x0d, 0xab, 0xcb, 0x89, 0xa3, 0xc4, 0x6e, 0xc4, 0xec, 0x3c, 0x07, 0x35, 0x86, 0x5c, 0x1f,
	0x94, 0x0a, 0xc2, 0xfa, 0x0e, 0x82, 0x09, 0x8e, 0x7d, 0x5e, 0x1d, 0x09, 0xfa, 0x60, 0x92, 0x1d,
	0x96, 0xe2, 0x9c, 0x3e, 0xa0, 0x95, 0x97, 0x99, 0xf6, 0x15, 0xc4, 0x75, 0xf9, 0x3c, 0xd6, 0xea,
	0x3c, 0xe1, 0x44, 0x26, 0x39, 0xa0, 0x08, 0x03, 0x3f, 0x02, 0x15, 0x71, 0x5e, 0x6a, 0x35, 0xc5,
	0xb9, 0xec, 0x3d, 0x9a, 0x53, 0x61, 0x54, 0xa9, 0x37, 0xd5, 0xa3, 0x59, 0x11, 0x37, 0xcf, 0x05,
	0x25, 0x38, 0xf8, 0xa9, 0x01, 0xa6, 0x7d, 0x3b, 0x20, 0x0e, 0x71, 0x3c, 0xb7, 0xd5, 0x34, 0xc7,
	0x19, 0xfe, 0x60, 0x34, 0xac, 0x9e, 0x8f, 0xcd, 0x6a, 0x00, 0xcd, 0x54, 0xc3, 0x89, 0xee, 0x2c,
	0xec, 0x39, 0x79, 0x4e, 0x28, 0x8d, 0x85, 0x0f, 0xf9, 0x83, 0x56, 0x66, 0xf4, 0xd6, 0x68, 0x58,
	0x9d, 0x3d, 0xc1, 0xf2, 0x11, 0x7b, 0x23, 0x86, 0x4a, 0x8a, 0x0a, 0x93, 0x45, 0xfe, 0xcc, 0xe2,
	0xe8, 0x99, 0x9d, 0x48, 0x7a, 0x36, 0x33, 0x68, 0x4a, 0x87, 0xa2, 0xa9, 0x08, 0x55, 0x16, 0x45,
	0x80, 0x76, 0x4f, 0xfa, 0x6c, 0xe0, 0x36, 0xc1, 0x1d, 0x73, 0x32, 0xe9, 0x9e, 0xb1, 0x51, 0xb3,
	0x8a, 0x39, 0x7a, 0x26, 0x85, 0x39, 0x2e, 0x28, 0xa1, 0xd1, 0x3d, 0x1b, 0xe0, 0xc3, 0x3d, 0xb7,
	0x3b, 0x30, 0xa7, 0x18, 0x98, 0xed, 0xd9, 0x00, 0x1f, 0xee, 0x7b, 0x6e, 0x77, 0xa0, 0xd9, 0xb3,
	0xe2, 0x0e, 0x3d, 0x35, 0xeb, 0x80, 0x22, 0x0c, 0x9d, 0x2c, 0x71, 0x7a, 0x38, 0x24, 0x76, 0xcf,
	0x37, 0x2b, 0xf4, 0x15, 0x8a, 0x4f, 0x36, 0x36, 0x6a, 0x26, 0x9b, 0xa3, 0x67, 0xaa, 0x5c, 0x8e,
	0x0b, 0x4a, 0x68, 0xb0, 0x0f, 0xa6, 0xfc, 0x00, 0x9f, 0xbe, 0x6e, 0x87, 0xc7, 0x26, 0x60, 0x2b,
	0xfa, 0x0e, 0x4f, 0x33, 0x3e, 0xdd, 0x3f, 0xb6, 0xc3, 0x63, 0xdd, 0xe1, 0x48, 0xdc, 0x53, 0x94,
	0xe5, 0x8c, 0x07, 0x8a, 0x51, 0x0c, 0x8b, 0x71, 0xc0, 0xb0, 0xd3, 0x29, 0x2c, 0xc6, 0x41, 0x21,
	0x56, 0xdc, 0x53, 0x80, 0xcd, 0x7a, 0xa0, 0x18, 0x45, 0xfb, 0x07, 0x1d, 0xdd, 0x9c, 0x49, 0xfa,
	0x47, 0x86, 0x96, 0xf4, 0x8f, 0xe3, 0x42, 0x92, 0xa2, 0x22, 0x36, 0x32, 0x25, 0x04, 0xf8, 0xf0,
	0xaa, 0x39, 0x9b, 0x10, 0xe8, 0xb5, 0x86, 0x20, 0x4b, 0x39, 0x5b, 0xe6, 0xaa, 0x44, 0xa0, 0x06,
	0x41, 0xa8, 0x99, 0x73, 0x12, 0xa1, 0xa6, 0x27, 0xd4, 0x0a, 0x09, 0x35, 0x95, 0x50, 0x13, 0x84,
	0x75, 0x73, 0x5e, 0x22, 0xac, 0xeb, 0x09, 0xeb, 0x85, 0x84, 0x75, 0x95, 0xb0, 0x2e, 0x08, 0x1b,
	0xe6, 0x82, 0x44, 0xd8, 0xd0, 0x13, 0x36, 0x0a, 0x09, 0x1b, 0x2a, 0x61, 0x43, 0x10, 0x36, 0xcd,
	0x45, 0x89, 0xb0, 0xa9, 0x27, 0x6c, 0x16, 0x12, 0x36, 0x55, 0xc2, 0xa6, 0x20, 0x6c, 0x99, 0x50,
	0x22, 0x6c, 0xe9, 0x09, 0x5b, 0x85, 0x84, 0x2d, 0x95, 0xb0, 0x25, 0x08, 0xdb, 0xe6, 0x92, 0x44,
	0xd8, 0xd6, 0x13, 0xb6, 0x0b, 0x09, 0xdb, 0x2a, 0x61, 0x5b, 0x10, 0xea, 0xe6, 0xb2, 0x44, 0xa8,
	0xeb, 0x09, 0xf5, 0x42, 0x42, 0x5d, 0x25, 0xd4, 0x05, 0x61, 0xc7, 0x3c, 0x27, 0x11, 0x76, 0xf4,
	0x84, 0x9d, 0x42, 0xc2, 0x8e, 0x4a, 0xd8, 0xa1, 0x0d, 0x89, 0x3e, 0x17, 0x57, 0xcc, 0xf3, 0x49,
	0x43, 0x62, 0x06, 0x4d, 0x43, 0x52, 0xb4, 0xbc, 0x87, 0xee, 0x8a, 0xd4, 0x90, 0x98, 0xa5, 0xf6,
	0xf5, 0x04, 0x18, 0xbb, 0xf5, 0x46, 0x0b, 0xb6, 0xc0, 0x9c, 0xfc, 0x22, 0x0b, 0xff, 0x97, 0x3a,
	0xc5, 0x65, 0xde, 0x71, 0x57, 0x2e, 0x68, 0xdf, 0x04, 0xe0, 0x5d, 0x30, 0x2b, 0xbd, 0xad, 0xc3,
	0xff, 0x66, 0x46, 0x4a, 0xde, 0xe3, 0x57, 0xfe, 0x5f, 0x7c, 0x9e, 0x87, 0x37, 0xc0, 0x3c, 0xbf,
	0x27, 0xf9, 0xce, 0xb0, 0x9c, 0xba, 0x25, 0xb6, 0xae, 0xe4, 0x5a, 0xe1, 0x35, 0xf6, 0xad, 0xee,
	0xe9, 0xee, 0xbd, 0x01, 0xe6, 0x9b, 0xb8, 0x8b, 0x9f, 0x16, 0x7d, 0x07, 0x80, 0xf8, 0x33, 0x61,
	0x08, 0xff, 0x93, 0xf2, 0x49, 0x7f, 0x3d, 0x7c, 0x62, 0x02, 0x76, 0xc1, 0x0c, 0xfb, 0x2a, 0xf9,
	0xb7, 0x06, 0xca, 0xfb, 0x9a, 0x79, 0x1b, 0x4c, 0xa7, 0x3e, 0xa7, 0xc2, 0x0b, 0xf2, 0x38, 0x7f,
	0x71, 0x71, 0xef, 0x47, 0x8b, 0x1b, 0xfd, 0xe8, 0x92, 0x5d, 0xdc, 0xe4, 0x4b, 0xf8, 0xca, 0xaa,
	0x4e, 0x8c, 0xc7, 0xe3, 0x49, 0x8a, 0x06, 0x33, 0xe5, 0x98, 0x52, 0x23, 0x5d, 0xcc, 0x55, 0xd2,
	0x61, 0x49, 0x3f, 0x93, 0x48, 0x61, 0xa9, 0xbf, 0x7e, 0x49, 0x61, 0xe5, 0xfe, 0xba, 0x72, 0x30,
	0xc1, 0x1c, 0xd6, 0xff, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x80, 0x45, 0x7e, 0x85, 0x1b, 0x00,
	0x00,
}
